# Generated by Django 3.0.4 on 2020-03-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200319_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
